runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  
libraries:
  - name: ssl
    version: latest
from google.appengine.ext import vendor

# Add any libraries installed in the "lib" folder.
vendor.add('lib')